<h1>Platba</h1>

<form action="" method="post">
    <div>
        <label for="mail">Zadejte maila</label>
        <input type="text" name="mail" required>
    </div>
    <div>
        <label for="street">Zadejte vaši ulici (včetně čísla)</label>
        <input type="text" name="street" required>
    </div>
    <div>
        <label for="street">Zadejte vaši město</label>
        <input type="text" name="city" required>
    </div>
    <div>
        <label for="street">Zadejte PSČ</label>
        <input type="num" name="psc" required>
    </div>
    <div class="submit">
        <input type="submit" value="submit" name="submit" id="submit">
    </div>
</form>